fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
    subversion:
      repo: "https://github.com/Adaptavist/puppet-subversion"
  symlinks:
    subversion_config: "#{source_dir}"
